/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    
    public static void main(String[] args) {

        String formaGeometrica = args[0];

        if (args.length == 3) {

            // fazer retangulo
            int retangulolargura = Integer.parseInt(args[1]);
            int retanguloltura = Integer.parseInt(args[2]);

            for (int i = 1; i <= retanguloltura; i++) {

                for (int j = 1; j <= retangulolargura; j++) {
                    if (i == 1 || i == retanguloltura || j == 1 || j == retangulolargura) {
                        System.out.print("*");
                    } else {
                        System.out.print(" ");
                    }
                }
                System.out.println();
            }

        } else if (args.length > 3 || args.length < 2) {
            System.out.println("Tamanho do vetor incorreto");
        } else if (formaGeometrica.equals("triangulo")) {

            // fazer triangulo
            int altura = Integer.parseInt(args[1]);

            for (int i = 1; i <= altura; i++) {

                for (int j = altura; j >= i; j--) {
                    System.out.print(" ");
                }

                for (int j = 1; j <= i; j++) {
                    System.out.print("*");
                }

                System.out.println();
            }
        }

        else {

            // fazer losango
            int altura = Integer.parseInt(args[1]);

            for (int i = 1; i <= altura / 2 + 1; i++) {

                for (int j = i; j <= altura / 2; j++) {
                    System.out.print(" ");
                }

                for (int j = 1; j <= (2 * i - 1); j++) {
                    System.out.print("*");
                }

                System.out.println();
            }
            for (int i = altura / 2; i >= 1; i--) {
                // Espaços à esquerda
                for (int j = altura / 2; j >= i; j--) {
                    System.out.print(" ");
                }
                // Asteriscos
                for (int j = 1; j <= (2 * i - 1); j++) {
                    System.out.print("*");
                }
                System.out.println();
            }
        }
    }
}